-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 20:22:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema iFudi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iFudi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iFudi` DEFAULT CHARACTER SET latin1 ;
USE `iFudi` ;

-- -----------------------------------------------------
-- Table `iFudi`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iFudi`.`usuario` (
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NULL,
  `nome` VARCHAR(100) NULL,
  `cpf` VARCHAR(11) NULL,
  `rua` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iFudi`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iFudi`.`cliente` (
  `usuario_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_email`),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_email`)
    REFERENCES `iFudi`.`usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iFudi`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iFudi`.`categoria` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iFudi`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iFudi`.`vendedor` (
  `usuario_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_email`),
  CONSTRAINT `fk_Vendedor_usuario1`
    FOREIGN KEY (`usuario_email`)
    REFERENCES `iFudi`.`usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iFudi`.`restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iFudi`.`restaurante` (
  `cnpj` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `categoria_id` INT NOT NULL,
  `vendedor_usuario_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cnpj`),
  INDEX `fk_restaurante_categoria1_idx` (`categoria_id` ASC) ,
  INDEX `fk_restaurante_vendedor1_idx` (`vendedor_usuario_email` ASC) ,
  CONSTRAINT `fk_restaurante_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `iFudi`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurante_vendedor1`
    FOREIGN KEY (`vendedor_usuario_email`)
    REFERENCES `iFudi`.`vendedor` (`usuario_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iFudi`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iFudi`.`pedido` (
  `id` INT NOT NULL,
  `cliente_usuario_email` VARCHAR(45) NOT NULL,
  `tempoEstimado` INT NULL,
  `data` VARCHAR(10) NULL,
  `restaurante_cnpj` VARCHAR(45) NOT NULL,
  `frete` DOUBLE NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_cliente1_idx` (`cliente_usuario_email` ASC) ,
  INDEX `fk_pedido_restaurante1_idx` (`restaurante_cnpj` ASC) ,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_usuario_email`)
    REFERENCES `iFudi`.`cliente` (`usuario_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_restaurante1`
    FOREIGN KEY (`restaurante_cnpj`)
    REFERENCES `iFudi`.`restaurante` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iFudi`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iFudi`.`avaliacao` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `votacao` INT NULL,
  `pedido_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avaliacao_pedido1_idx` (`pedido_id` ASC) ,
  CONSTRAINT `fk_avaliacao_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `iFudi`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iFudi`.`promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iFudi`.`promocao` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(500) NULL,
  `porcentagem` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iFudi`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iFudi`.`produto` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `promocao_id` INT NOT NULL,
  `restaurante_cnpj` VARCHAR(45) NOT NULL,
  `preco` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_promocao1_idx` (`promocao_id` ASC) ,
  INDEX `fk_produto_restaurante1_idx` (`restaurante_cnpj` ASC) ,
  CONSTRAINT `fk_produto_promocao1`
    FOREIGN KEY (`promocao_id`)
    REFERENCES `iFudi`.`promocao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_restaurante1`
    FOREIGN KEY (`restaurante_cnpj`)
    REFERENCES `iFudi`.`restaurante` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iFudi`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iFudi`.`item` (
  `id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `quantidade` INT NULL,
  `precoTotal` DOUBLE NULL,
  `pedido_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itens_produtos1_idx` (`produto_id` ASC) ,
  INDEX `fk_item_pedido1_idx` (`pedido_id` ASC) ,
  CONSTRAINT `fk_itens_produtos1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `iFudi`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `iFudi`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iFudi`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iFudi`.`pagamento` (
  `id` INT NOT NULL,
  `valor` VARCHAR(45) NULL,
  `pedido_id` INT NOT NULL,
  `formaPagamento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pagamento_pedido1_idx` (`pedido_id` ASC) ,
  CONSTRAINT `fk_pagamento_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `iFudi`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
